"""empty message

Revision ID: 415806ae4448
Revises: ef110e20da1e
Create Date: 2024-04-09 12:10:41.629813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415806ae4448'
down_revision = 'ef110e20da1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.alter_column('suscripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.alter_column('suscripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
