"""empty message

Revision ID: a6aec9ac2377
Revises: eaca36a7d34e
Create Date: 2024-05-20 20:49:43.013527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aec9ac2377'
down_revision = 'eaca36a7d34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
