"""empty message

Revision ID: a9497d3814ae
Revises: 
Create Date: 2024-04-10 14:05:02.002573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9497d3814ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('suscripcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('estadisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ultimo_examen', sa.Float(), nullable=True),
    sa.Column('media_examen', sa.Float(), nullable=True),
    sa.Column('media_10_examenes', sa.Float(), nullable=True),
    sa.Column('mejor_racha', sa.Integer(), nullable=True),
    sa.Column('porcentaje_aciertos', sa.Float(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(), nullable=False),
    sa.Column('respuesta_a', sa.String(), nullable=False),
    sa.Column('respuesta_b', sa.String(), nullable=False),
    sa.Column('respuesta_c', sa.String(), nullable=False),
    sa.Column('respuesta_d', sa.String(), nullable=False),
    sa.Column('respuesta_correcta', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadisticas_preguntas',
    sa.Column('estadistica_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('fallos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estadistica_id'], ['estadisticas.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('estadistica_id', 'pregunta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas_preguntas')
    op.drop_table('preguntas')
    op.drop_table('estadisticas')
    op.drop_table('users')
    op.drop_table('estudiantes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
