"""empty message

Revision ID: db014c14a80c
Revises: 04f2698e642a
Create Date: 2024-05-11 13:27:36.419071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db014c14a80c'
down_revision = '04f2698e642a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('estadisticas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_5_examenes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultimos_5_examenes', sa.String(), nullable=True))
        batch_op.drop_column('media_10_examenes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadisticas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_10_examenes', sa.FLOAT(), nullable=True))
        batch_op.drop_column('ultimos_5_examenes')
        batch_op.drop_column('media_5_examenes')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###
